### ISSUE TITLE
2つ以上のカメラをBaseカメラのスタックに積めないときがある

### ISSUE THREAD

**Issue by mtmt** [upm-packages/CameraStackHandler#5]
### 何が起きているか?

例えば

- CameraA (Base)
- CameraB (Base) ← AddOverlayCameraToCameraStackコンポーネントを追加
- CameraC (Base) ← AddOverlayCameraToCameraStackコンポーネントを追加

としたときに，順序によってはカメラAのスタックが

1. CameraB (Overlay)
1. CameraC (Overlay)

となるが，うまくいかないときは

1. CameraB (Overlay) もしくは CameraC (Overlay)

と1つだけになってしまう。

### 原因

カメラxをBase → Overlayに変換する際に，カメラxが保持しているスタックが採用されないから?

**Comment by monry** [comment]
@mtmt
追加対象の Base カメラを探す際に、RenderType = Base な Camera のウチ `Camera.depth` （インスペクタでは Priority というフィールド）が最も大きいモノを採用しているので、 CameraA の depth を大きい値にしておくと冪等性が保てるかと思います。

本来であれば Base カメラは1個しかないコトが殆どだと思うので、問題無い想定なんですが、処理のタイミング的に RenderType = Overlay になるのは `AddOverlayCameraToCameraStack.Start()` なので、複数シーンを同時に読み込んだりする場合、検索時点で間に合わない可能性はありうるかなぁと思います。

（この件については README に追記しておきました。）

**Comment by monry** [comment]
@mtmt
追加対象の Base カメラを探す際に、RenderType = Base な Camera のウチ `Camera.depth` （インスペクタでは Priority というフィールド）が最も大きいモノを採用しているので、 CameraA の depth を大きい値にしておくと冪等性が保てるかと思います。

本来であれば Base カメラは1個しかないコトが殆どだと思うので、問題無い想定なんですが、処理のタイミング的に RenderType = Overlay になるのは `AddOverlayCameraToCameraStack.Start()` なので、複数シーンを同時に読み込んだりする場合、検索時点で間に合わない可能性はありうるかなぁと思います。

（この件については README に追記しておきました。）

**Comment by mtmt** [comment]
ありがとうございます。
> CameraA の depth を大きい値にしておく
が良さそうですね。

再生時はそれで想定した通りになりそうです!

一方，編集中のゲームビューの表示は，カメラのPriority通りになるはずなので若干編集しづらいかもですが，シーンビューの方で確認すればまずは大丈夫かなと思います。

**Comment by mtmt** [comment]
ありがとうございます。
> CameraA の depth を大きい値にしておく
が良さそうですね。

再生時はそれで想定した通りになりそうです!

一方，編集中のゲームビューの表示は，カメラのPriority通りになるはずなので若干編集しづらいかもですが，シーンビューの方で確認すればまずは大丈夫かなと思います。

**Comment by monry** [comment]
あ、というか、Overlay に変換するときに自身の Stack を引き連れて行けば良いんですよね。
（本文にも書かれていますが。）

てことで、その機能を追加しますね。
Overlay カメラ側の並び順は v1.2.0 で実装した Priority で制御出来るので、これで解決…かな？

**Comment by monry** [comment]
@mtmt 
[コチラの対応](https://github.com/upm-packages/CameraStackHandler/pull/8) で如何でしょう？

**Comment by mtmt** [comment]
@monry 
あ，これ良いですね! 先のPriority指定と相まって柔軟に操作できそうです。
実際にちらっと使ってみたんですが，好きなカメラを手前に持ってこれて，かつ，全部重ねもできるので，制作時のイテレーションが早く回せそうな感じです。ありがとうございます!

**Comment by monry** [comment]
では、明日にでもマージとリリースしちゃいますねー👍
